name: Coverage
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Generate coverage report
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ".[dev,docs]"
          python -m ipykernel install --user --name=scml
          yes | python -m pip uninstall negmas
          python -m pip install git+https://github.com/yasserfarouk/negmas.git
      - name: "Get coverage data by running tests"
        run: |
          pip install pytest pytest-cov
          pytest --cov=src/scml --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.codecov }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
