name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    env:
      USING_COVERAGE: '3.12'

    strategy:
      matrix:
        python-version: ['3.12', '3.11']

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel pytest
          python -m pip install --upgrade  virtualenv
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
          python -m ipykernel install --user --name=scml
      - name: "Run pytest for ${{ matrix.python-version }}"
        run: "python -m pytest tests"

  package:
    name: "Build & verify package"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: '3.12'

      - name: "Install pep517 and twine"
        run: "python -m pip install --upgrade pip setuptools wheel pytest twine"
      - name: "Build package"
        run: "python setup.py sdist bdist_wheel"
      - name: "List result"
        run: "ls -l dist"
      - name: "Check long_description"
        run: "python -m twine check dist/*"
